### PR TITLE
Persona Bar Pages goes blank when no EDIT permission

### PR DESCRIPTION
**Pull request by mikebigun**
fixes https://github.com/dnnsoftware/Dnn.AdminExperience/issues/436

There are multiple corrections:
1. I reverted some changes for `PersonaBarPageTreeviewInteractor` I did in 5fc4c549e2fc8582691b4c3001ee6028535103de previously, I found that was not a correct solution
2. Deprecated life-cycle methods are replaced with a new ones
3.  `includeInMenu` property is fixed to check whether it is undefined or not

Pages treeview works fine now in both Platform and Evoq.
Also, without `EDIT` rights user is not able to modify page settings but is possible to add child pages and add new modules to the page:

image

### CODE REVIEW

**Comment by sleupold** [comment]
Permissions should not just check for "Edit" and "view", but should support granular permissions like in Evoq as well (in case a 3rd party permission provider is used).

**Comment by daguiler** [comment]
So @mikebigun there is no actual change in permissions behavior in this PR correct? It's all about fixing front-end React bugs

**Comment by mikebigun** [comment]
Right, only UI.

**Comment by mikebigun** [comment]
Dear approvers, just want to follow up this one. Let me know if you have any concerns.

**Review by daguiler — APPROVED** [review]

**Review by valadas — APPROVED** [review]

**Pull request merged**
