### PR TITLE
DNN-25490 Persona Bar: Users: Role Names overflowing into next line

### PR DESCRIPTION
**Pull request by noor-zubair**
Fix delivers to issue [#106](https://github.com/dnnsoftware/Dnn.AdminExperience/issues/106)

### CODE REVIEW

**Review by tpluscode — CHANGES_REQUESTED** [review]
I don't think it's enough to just resize columns. Long enough text would still overflow, right?

To make it more future-proof, I'd rather see a CSS [`text-overflow: ellipsis`](https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/) maybe?

**Comment by noor-zubair** [comment]
Role name field has max length defined which is 50 and the example role name used is of max length. So it will not overflow.
db

**Comment by sleupold** [comment]
@noor-zubair, @tpluscode 
there is already a feature request to increase length of this field (which makes sense for roles synched from AD), i.e. I agree to the suggestion from @tpluscode.

**Comment by noor-zubair** [comment]
@tpluscode ,
I am implementing the suggestion, thanks.

**Comment by mikebigun** [comment]
@tpluscode @sleupold 

See text-overflow in action:

image

**Review by tpluscode — APPROVED** [review]
@dnnsoftware/approvers, looking good? :)

**Review by bdukes — APPROVED** [review]

**Comment by sleupold** [comment]
looks fine for me

**Pull request merged**
