### PR TITLE
Error message while deleting localized version of home page

### PR DESCRIPTION
**Pull request by mikebigun**
fixes https://github.com/dnnsoftware/Dnn.AdminExperience/issues/990

Added `IsSpecial` property to be passed to UI to validate if page is allowed to be deleted.

### CODE REVIEW

**Comment by mikebigun** [comment]
Dear @approvers, please raise your concerns if any.

**Comment by sleupold** [comment]
looks fine to me

**Review by daguiler — APPROVED** [review]
LGTM. Is 3.0.x mapping to 9.4.x?

**Review by valadas — APPROVED** [review]
Looks good to me but yes 3.0.x targets Dnn 9.4.0 release, I will try to retarget development

**Comment by valadas** [comment]
Tried changing this to target development but it is too different. @ohine do we need to update development with changes in the release branch or does @mikebigun need to rebase from development? Or do we just take this into 9.4.0 release, it does not look like much risk...

**Comment by mikebigun** [comment]
@ohine, to move this forward, let us know please whether we can stay with `release/3.0.x` or should I re-target this to `development`?

**Comment by daguiler** [comment]
@mikebigun Milestone is now 4.0.0 so let's re-target please

**Comment by mikebigun** [comment]
Closing this one in favor of https://github.com/dnnsoftware/Dnn.AdminExperience/pull/996 which is now goes to `development`.

**Pull request closed without merging**
