### PR TITLE
DNN-22335: Changes for DNN-18264 need to be update for SIteSettings p…

### PR DESCRIPTION
**Pull request by Mohtshum**
Fix bug (#144|https://github.com/dnnsoftware/Dnn.React.Common/issues/144)

Changes obtained when Update Dnn-file-upload component by following commands
- yarn add dnn-file-upload
- yarn build

### CODE REVIEW

**Review by tpluscode — COMMENTED** [review]
@ohine should we also rebuild site-settings-bundle.js?

**Comment by ohine** [comment]
@tpluscode Does yarn not update the bundles automatically when building in release mode?

**Comment by tpluscode** [comment]
Apparently not. I see no yarn in `Dnn.PersonaBar.SiteSettings` nor in for example `Licensing`

**Comment by Mohtshum** [comment]
These changes are required for [#144](https://github.com/dnnsoftware/Dnn.React.Common/issues/144). Please have a look to verify it for merge ASAP

**Review by tpluscode — CHANGES_REQUESTED** [review]
To be sure, please commit the bundle.js file

**Comment by Mohtshum** [comment]
PR to update the Dnn-file-upload is should be in  Library/Dnn.PersonaBar.UI/admin/personaBar/Bundle.Web

 https://github.com/dnnsoftware/Dnn.AdminExperience/pull/58

**Pull request closed without merging**
