### PR TITLE
Fixes the Pages Module after the dependencies updates

### LINKED ISSUE #149: Pages.Web does not build after last greenkeeper merge
## Description of bug
Cannot build Pages.Web after greenkeeper upgraded webpack and other dependencies versions, see #117 

## Steps to reproduce
List the steps to reproduce the behaviour:
1. Using the command line, navigate to Pages.Web
2. Run yarn install
3. Run yarn build
4. Notice errors

## Current result
Gives tons of errors

## Expected result
Project should build

## Error log
Many, mainly the webpack.config needs updating then a new series of errors due to many dependencies version upgrades. Too many to list, every time one is fixed, a new one appears.

## Additional context
I am working on a PR for this project at the moment, discussed this with @ohine @donker Matt (don't know his github alias) and @mitchelsellers 

## Affected version

* [x] 9.3.xxxx (nightly build)
* [ ] 9.2.2
* [ ] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

### PR DESCRIPTION
**Pull request by valadas**
## Summary
Since greenkeeper updated many things including most dependencies and webpack, the Pages module was not able to build
This pull request fixes many of those issues including:
- webpack.config.js changes
- babelrc changes
- code changes (though still using some deprecated methods)
- Updated to use the new common components structure

## What is left to do
- I tested the module with the new common components and everything appears to be working
- However there is still one use of an UNSAFE_ (deprecated) method which I could not replace without causing and endless loop. It works fine but we will need to get that sorted out before React 17, for now though, it works.

closes #149

### CODE REVIEW

**Comment by valadas** [comment]
@mtrutledge , @ohine , @bdukes , @mitchelsellers I think this is good to merge now, happy reviewing :)

**Comment by david-poindexter** [comment]
I believe this one should be related to #149, correct?

**Comment by valadas** [comment]
@nvisionative you are correct, forgot to link the issue, updated my pr message. Will take a look at the conflict.

**Comment by valadas** [comment]
Merge conflict resolved.

**Review by ohine — APPROVED** [review]

**Review by mitchelsellers — APPROVED** [review]

**Pull request merged**
