### PR TITLE
DNN-29429: Fix SMTP Server Tab UI Issue

### LINKED ISSUE #1090: UI Issue on Settings > Servers > Server Settings >  SMTP Server Tab
## Description of bug
When any user who do not have the SMTP Settings permissions on the SMTP Server tab, a.k.a, an Administrator user; navigates to the Settings > Servers > Server Settings >  SMTP Server tab, an extra redundant horizontal-ruler is visible in the right pane of the tab, which is expected to be empty.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Log in as an Administrator user.
2. Go to Persona Bar > Settings > Servers.
3. Click on "Server Settings" Tab.

## Current result
An extra redundant horizontal-ruler is visible in the right pane of the "Server Settings" tab.

## Expected result
The right pane of the "Server Settings" tab should be totally empty without any visual elements for any user who do not have the SMTP Settings permissions.

## Screenshots
image

## Error log
N/A

## Additional context
N/A

## Affected version
* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

### PR DESCRIPTION
**Pull request by kkadir**
Fixes #1090 

## Summary
The `<div className="tooltipAdjustment border-bottom">` tags are moved after the `smtpSettingsVisible` flag. This assures that a horizontal-line is visible only if that block is visible.

**[Confirmation Video](https://drive.google.com/open?id=13PtM4j6CqOCJaaAf-JeOSRsq9CpNH2OP)**

### CODE REVIEW

**Review by valadas — DISMISSED** [review]

**Review by bdukes — DISMISSED** [review]

**Review by tingung — DISMISSED** [review]

**Review by v-karbovnichy — DISMISSED** [review]

**Comment by mitchelsellers** [comment]
@kkadir Any chance this change could get resubmitted aginst the 3.0.0 release branch?  We are still working some items for 9.4.0 and I would like to get this in?

**Comment by kkadir** [comment]
Hello @mitchelsellers, sorry for the delay, sure I will rebase it right away.

**Comment by kkadir** [comment]
Rebasing it messed the PR so please close this one as I will open a new PR based on the 3.0.X Release branch.

**Comment by mitchelsellers** [comment]
Will do!  FYI - This will come as part of 9.4.1, as we have closed 9.4.0 items.

**Comment by kkadir** [comment]
#1124 created with the same changes based on `release/3.0.x`, also thanks for the update @mitchelsellers.

**Pull request closed without merging**
