### PR TITLE
Fixes #186 

### LINKED ISSUE #186: Extension Settings: Control Selection
## Description of bug
It is impossible to select the right control in the UI: 
image
I always need to open the developer tools to verify my selection 

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to PersonaBar/Settings/extensions/ExtensionSettings
2. Edit/add a ModuleDefinition
3. Try to select the right control

## Affected version

* [x] 9.2.2

### PR DESCRIPTION
**Pull request by SCullman**
## Summary
Only the layout of thegrid  has changed. Source folder and Souce file are now on its own row.

### CODE REVIEW

**Comment by SCullman** [comment]
I expect that the change is trivial. I was not able to test my changes on my own.
Looks like the instructions [here](https://www.dnnsoftware.com/community-blog/cid/155391/dnn9-adding-a-reactjs-app-to-persona-bar) are no longer valid. 
If you have any updates on this process, it would be very much appreciated.

**Comment by mitchelsellers** [comment]
@SCullman I'm sorry we had a number of changes that have came in since your commit, can you re-validate this change and adjust to resolve the conflicts?

**Comment by SCullman** [comment]
@mitchelsellers No problem. At least I can do now a 

```bash
yarn install
yarn build
```
to compile the bundle. Nice, that was what I was looking for 👍

**Review by mitchelsellers — APPROVED** [review]
Thanks sir!  We want this included in the RC build for validation

**Review by valadas — APPROVED** [review]
I fixed the merge conflict and tested locally, had to change one GridSystem for a GridCell because GridSystem does not work with a single child. Other than that , this is good.

**Comment by valadas** [comment]
Renders like this:
image


This section of the module would use some other improvements, there is a lot (too much) padding in too many nested elements, but this is a good step forward.

**Pull request merged**
