### PR TITLE
Fix to display IP Filter settings correctly

### LINKED ISSUE #1078: IP address filtering UI is not reflecting the settings correctly
## Description of bug
IP address filtering UI is not reflecting the settings correctly. 

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to Settings -> Security -> Member Accounts -> Member Management 
2. Toggle "On" Enable IP Address Checking And Save 
3. Go to Settings -> Security -> Login Settings ->Login IP Filters 
4. Click "Add New Filters" 
5. Enter 192.168.0.1 into "First IP" 
6. Click "Save" 
7. Edit the filter

## Current result
First IP input text field is blank. Similar behavior for other fields. 

## Expected result
First IP input text field should display the saved value. Other fields should display the saved value. 

## Screenshots
If applicable, provide screenshots to help explain your problem.
image
Reproduction video - https://drive.google.com/open?id=140U9IJAe5kN4SIgxRzIy6fe2GBUgoYHE

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

### PR DESCRIPTION
**Pull request by tingung**
Fixes #1078 

## Summary

Fix to display IP Filter settings correctly
- Code refactor and minor bugs listed below
- Update state with the value from json response to ensure IP Filter
object in UI is updated
- Move specificityOptions and typeOptions initialization to constructor
- Move all the validation of the form upon saving to reduce code complexity
- Replace toggle option of RuleSpecificity to use const String of
IP_RANGE and  SINGLE_IP to make the code simpler and more readable
- Move code to clear SubnetMask just before update to prevent SubnetMask
become blank when user switch in between IP_RANGE and SINGLE_IP option

Confirmation video - https://drive.google.com/open?id=1ntAIguD-GgT5ZuAqsLtEscN76-M_qbXG

### CODE REVIEW

**Comment by tingung** [comment]
@dnnsoftware/approvers anyone can review this PR?

**Comment by mitchelsellers** [comment]
We are in the middle of a release cycle.  Currently with this targeting the Development Branch it will be considered for inclusion in the 10.0 release.

Once we get the 9.4.0 RC & Actual Release done we will resume processing PR's that are targeting the release branch for inclusion in 9.4.1.

**Review by daguiler — APPROVED** [review]
Works correctly.

**Comment by daguiler** [comment]
Hi @tingung, can you please close and target `release/3.0.x` branch? Thank you

**Comment by tingung** [comment]
Hi @daguiler , you means merge the changes to https://github.com/dnnsoftware/Dnn.AdminExperience/tree/release/3.0.x?

**Comment by tingung** [comment]
Closing this PR. Changes are merged to release/3.0.x branch. Refer to this PR - https://github.com/dnnsoftware/Dnn.AdminExperience/pull/1146

**Pull request closed without merging**
