### PR TITLE
Site Settings > Site Behavior > Site Aliases: Edit Alias behaves as Add Alias

### LINKED ISSUE #336: Site Settings > Site Behavior > Site Aliases: Edit Alias behaves as Add Alias
## Description of bug
ISSUE 1: the table with existing aliases has no headers
ISSUE 2:  Site Alias textbox is empty. Because in fact, Edit Alias is working as Add Alias

## Steps to reproduce
##ISSUE 1: the table with existing aliases has no headers
1) Navigate to PB > Site Settings > Site Behavior > Site Aliases
2) Press F5 to refresh

##ISSUE 2:  Site Alias textbox is empty. Because in fact, Edit Alias is working as Add Alias
1) Navigate to PB > Site Settings > Site Behavior > Site Aliases
2) Press F5 to refresh
3) Click Add Alias again
4) Add a new alias, for example platform-latest.dnndev.me. Leave all other fields with default values.
5) Click Save
6) Click the pencil icon to edit the newly created alias

## Current result
1. The table with existing aliases has no headers.
image

2. Site Alias textbox is empty. Because in fact, Edit Alias is working as Add Alias
image

## Expected result
1. header should be present for site Aliases table.
image

2. Site alias should be editable
image
## Affected version
* [ ] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [ ] Internet Explorer
* [ ] Edge

### PR DESCRIPTION
**Pull request by anishmishra978**
Fixes #336

### CODE REVIEW

**Review by daguiler — CHANGES_REQUESTED** [review]
I added a new alias and then clicked the edit icon. The form was correctly populated, but then the Save button created a validation error in the "Site Alias" textbox. Also, please use spaces for indentation.

**Review by valadas — CHANGES_REQUESTED** [review]
I experienced the same behaviour as previously noted. After that, changing the alias and clicking save again does work but if go to edit it again, the field is blank like previously.
Hitting F5 and going back does work though.

**Comment by daguiler** [comment]
Yes. @anishmishra978 check out following repro steps:

1) add new alias "platform.com"
2) click the edit icon on the newly added alias
3) click Save --> Validation error "The site alias is invalid"
4) click Cancel
5) click Edit again --> Site Alias is blank
6) Type "platform.com" in the blank textbox
7) click Save --> The alias already exists (it's trying to add a new alias)

**Comment by valadas** [comment]
#343 should have fixes this, closing it.

**Pull request closed without merging**
