### PR TITLE
DNN-31578 - Deleted page can still be selected as parent page - second repository

### PR DESCRIPTION
**Pull request by berkarslan-xo**
Partially Fixes https://github.com/dnnsoftware/Dnn.Platform/issues/2919 (There are total of 2 PRs; for the other PR, you can check: https://github.com/dnnsoftware/Dnn.Platform/pull/2925 ).
## Summary

A new parameter named as "includeDeletedChildren" is added to filter out the deleted child pages.

Demo: https://drive.google.com/open?id=1yg6OuVuLMbwCbBlFHXDqQa8Abd3WPIn_

Note: This PR should be merged AFTER https://github.com/dnnsoftware/Dnn.Platform/pull/2925. CI fails since the dependent PR is not merged yet.

### CODE REVIEW

**Review by mitchelsellers — APPROVED** [review]
Thanks for the resubmit on this, I appreciate it!

**Review by bdukes — APPROVED** [review]

**Comment by berkarslan-xo** [comment]
CI fails since it requires https://github.com/dnnsoftware/Dnn.Platform/pull/2925 to be merged first. I suppose packages.config needs to be updated after the merge too.

**Comment by valadas** [comment]
Hmm, I was sure that got merged, it is now, but we need to wait for dependabot then we will be able to merge this. @mitchelsellers when you have a minute, if you can rerun the pipeline with publish task enabled, Dependabot should update the PRs to this new one after I merged the PR in Platform. Thanks

**Review by valadas — APPROVED** [review]

**Pull request merged**
