### PR TITLE
Link to DNNdocs

### PR DESCRIPTION
**Pull request by Tychodewaard**
I think the link to documentation should be a link to DNNDocs

### CODE REVIEW

**Review by bdukes — APPROVED** [review]

**Review by mitchelsellers — APPROVED** [review]

**Review by valadas — APPROVED** [review]

**Comment by valadas** [comment]
@Tychodewaard  this is currently targetting development which means it would be included in Dnn 10, would you like to re-target the release/3.0.x branch for inclusion in Dnn 9.4.1 ?

**Comment by Tychodewaard** [comment]
@valadas I really want to but how do I do that? BTW: I would expect that I am not in charge of deciding whether it should be in what release. That would be too much honour :-) 

I can see you added it to 9.4.1. on August 1 and yesterday to milestone 9.4.1 and 10.0.0.
Is there something else needed or to be done on my side?

**Comment by bdukes** [comment]
It looks like this change was incorporated into a previous commit already: 147748a2889f67e8690d712cdb8bd39385794a27

We'll go ahead and close this one, but thank you so much for starting the contribution, we really do appreciate it.

**Comment by david-poindexter** [comment]
Yes, I made this change a while back and it is already in 9.4.0.  Thanks.

**Pull request closed without merging**
