### PR TITLE
PB Tooltip hovering giving JS errors

### LINKED ISSUE #319: Platform > PB: Hovering over tooltips generate Javascript errors for maximum update of setState in Card component of react-portal-tooltip
## Description of bug
Platform > PB: Hovering over tooltips generate Javascript errors for maximum update of setState in Card component of react-portal-tooltip

## Steps to reproduce
After login as Host
 Hover over the following tooltips:
- Site Settings > Site Behavior > Default Pages > Registration Page
- Site Settings > Site Behavior > User Profiles > Add Field > Required (only reproducible in Platform)
- Site Settings > Site Behavior > User Profiles > Add Field > Data Type (only reproducible in Platform)

## Current result
Tooltip is not appearing and errors in debugger of browser
"export-bundle.js?cdv=52:90 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. "

## Expected result
Tooltip should appear

## Screenshots
image

## Error log
react-dom.development.js?61bb:55 Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at invariant (react-dom.development.js?61bb:55)
    at scheduleWork (react-dom.development.js?61bb:18406)
    at Object.enqueueSetState (react-dom.development.js?61bb:12313)
    at ProxyComponent.Component.setState (react.development.js?72d0:372)
    at ProxyComponent.updateSize (index.js?5a1b:342)
    at ProxyComponent.updateSize (react-hot-loader.development.js?c2cb:587)
    at ProxyComponent.componentDidUpdate (index.js?5a1b:333)
    at ProxyComponent.componentDidUpdate (react-hot-loader.development.js?c2cb:577)
    at commitLifeCycles (react-dom.development.js?61bb:15976)
    at commitAllLifeCycles (react-dom.development.js?61bb:17262)
invariant @ react-dom.development.js?61bb:55
scheduleWork @ react-dom.development.js?61bb:18406
enqueueSetState @ react-dom.development.js?61bb:12313
Component.setState @ react.development.js?72d0:372
updateSize @ index.js?5a1b:342
getPortalSettings @ react-hot-loader.development.js?c2cb:587
componentDidUpdate @ index.js?5a1b:333
componentDidMount @ react-hot-loader.development.js?c2cb:577
commitLifeCycles @ react-dom.development.js?61bb:15976
commitAllLifeCycles @ react-dom.development.js?61bb:17262
callCallback @ react-dom.development.js?61bb:149
invokeGuardedCallbackDev @ react-dom.development.js?61bb:199
invokeGuardedCallback @ react-dom.development.js?61bb:256
commitRoot @ react-dom.development.js?61bb:17458
completeRoot @ react-dom.development.js?61bb:18912
performWorkOnRoot @ react-dom.development.js?61bb:18841
performWork @ react-dom.development.js?61bb:18749
performSyncWork @ react-dom.development.js?61bb:18723
batchedUpdates$1 @ react-dom.development.js?61bb:18936
batchedUpdates @ react-dom.development.js?61bb:2150
dispatchEvent @ react-dom.development.js?61bb:4899
react-dom.development.js?61bb:15749 The above error occurred in the <Card> component:
    in Card

Consider adding an error boundary to your tree to customize error handling behavior.

## Affected version
* [x] 9.3.0

### PR DESCRIPTION
**Pull request by Mhtshum**
- adding tooltipStyle to Label

Fixes #319

### CODE REVIEW

**Comment by Mhtshum** [comment]
Required Tooltip is not perfectly aligned, currently.

**Review by valadas — CHANGES_REQUESTED** [review]
I have tested these changes, it is ok but one of the labels does not align properly for the Required field and other labels in the same file work fine without specifying the tooltipStyle. I would like to investigate the root cause before merging this so we may have a better fix, this PR is more of a workaround in my opinion to a bigger underlying cause.

**Comment by valadas** [comment]
I have isolated the issue to only when tooltipMessage if of a specific lenght.
For instance, it fails with The user registration page for your site. but works fine if I just add an additional dot at the end.

Also the problem is an infine loop trying to show/hide the tooltip which may mean something about the transition making you loose mouse-over on the icon and when it hides, the hover works again, etc. I gonna try to make that reproducible in the storybook so we can identify the actual problem for this.

**Comment by valadas** [comment]
Found a related issue with react-portal-tooltip that we use in common here https://github.com/romainberger/react-portal-tooltip/issues/84

**Review by valadas — APPROVED** [review]

**Comment by valadas** [comment]
Well, I have spend most of the day trying to figure out what causes this:
- It only happens on some labels
- Adding or removing even one letter in the label appears to fix it
- I was not able to reproduce in any way in the storybook
- I was not able to reproduce in any way using just this component on a blank page
- We are not alone with this issue, see romainberger/react-portal-tooltip#84

For those reasons and because this PR actually works around the problem, I have approved but added comments near so that we know why those 3 labels are different and can revert when the underlying cause is found.

**Review by daguiler — APPROVED** [review]
Yes, I've spent a lot of time on this one yesterday as well, and could not get to a fix that would make me happy. Let's live with the workaround for now.

**Comment by bdukes** [comment]
Thanks for all the time spent on this @valadas & @daguiler. I appreciate that y'all aren't letting a little thing like this slide without some deeper investigation.  Good job, team! 🥇

**Comment by valadas** [comment]
@bdukes you are welcome, yeah, I found the PR strange because all others work without specific style so, like @daguiler , this is not my preffered way to solve it but it works, so at least with comments explaining it we know why they are different.

**Pull request merged**
