### PR TITLE
First steps towards improving the accessibility of the PersonaBar.

### PR DESCRIPTION
**Pull request by OllyHodgson**
## Summary

First attempt at fixing #32 and #34:

- Adds `aria-haspopup` and `aria-expanded` attributes to relevant icons in the main PersonaBar.
- When menus become visible, set `aria-expanded` to `true` (and back to `false` when they're hidden)
- Add alt text to the icons - via a `<title>` element when it's an SVG

Release Note: First steps towards improving the accessibility of the PersonaBar.

Testing Steps: Compare before and after using the accessibility pane in Firefox's developer tools. Would also be a good idea to get some help from someone using assistive technology.

This is my first pull request on DNN, so be gentle ;-)

### CODE REVIEW

**Comment by mitchelsellers** [comment]
@OllyHodgson At first review, this looks like a good fix.  I'll review in more detail later

**Comment by Cambridgeport90** [comment]
I am keeping an eye on this one. We have some members aside from myself using assistive tech in the @stormlighttech organization, so I'll see what we can do as well ... it's time we got involved in more projects anyways! Thanks again for this. Remember, anyone can get a free screen reader. go to [NVDA](https://nvda-project.org).

**Review by mitchelsellers — APPROVED** [review]
These changes look good and do not impact the usability of the site for people.  Lets get this approved if we can.

**Comment by Cambridgeport90** [comment]
Nice work, guys. I'm now wondering how I can add these changes into my existing site. I unfortunately don't have two environments at the moment, so, I'll need the next alternative, if you have one. Thanks.

**Comment by OllyHodgson** [comment]
@mitchelsellers I haven't signed the CLA yet - and the automagical integration doesn't seem to exist in this repo.

**Comment by OllyHodgson** [comment]
@Cambridgeport90 The 3 files I modified live under /DesktopModules/Admin/Dnn.PersonaBar. If you're using 9.2.1 you could simply copy the patched files from this pull request over the top of the existing ones.

Assuming it's an accessible tool, http://www.nvquicksite.com/ can set up fresh instances of DNN on your PC super quickly and easily.

**Comment by Cambridgeport90** [comment]
Thanks again, guys.

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by Cambridgeport90** [comment]
Thanks! I’m going to do that when I get off work today, I think. And thanks for reminding me about the DNnQuickSite tool I had forgotten it existed. I’ve never used it, though I think I might in future.

**Comment by ohine** [comment]
@OllyHodgson Are you still working on more items to bundle in this pull request? Or should we merge it as it stands?

**Review by ohine — APPROVED** [review]

**Comment by OllyHodgson** [comment]
@ohine This one is good to go (unless any bugs are found). I can file more PRs for further work as time permits. 

(do I need to do anything more? I'm new to this githubbing thing!)

**Comment by mitchelsellers** [comment]
@OllyHodgson We will go ahead and merge this one in, you can for sure submit additional items.  Future PR's will be approved/processed faster since we will not have the issue with the CLA agreement that we had this time.

We greatly appreciate your contributions to this effort!

**Comment by ashishpd** [comment]
I am wondering how I can test this.. Are there any instructions on what to look for in the Firefox Accessibility tool?

**Comment by Cambridgeport90** [comment]
What exactly do you need to test? I can help there, I hope.

**Comment by OllyHodgson** [comment]
@ashishpd Using the Firefox accessibility dev tools you should be able to see after this patch that the main menu items in the PersonaBar now have text labels! Before, they did not, so they were effectively invisible to assistive tech.

You could also install/enable NVDA, ChromeVox or VoiceOver (dependent on your platform) and listen to the PersonaBar being read aloud. I seem to remember NVDA can also show you the text being read out.

Sorry I can't be much more specific - I've moved jobs (and to another continent!) and don't have access to a Windows machine or DNN install right now.

**Comment by ashishpd** [comment]
Thanks @OllyHodgson and @Cambridgeport90 for getting back. Here's a video where I've tried to explain the update: https://www.youtube.com/watch?v=xjZa8PQ8qiE&list=PLIx1M8IdVvqafFiDozHCf79woQEuT2ko3&index=4

Hopefully, it aligns with what you did here.

**Comment by Cambridgeport90** [comment]
You’re quite welcome. I’ll be watching the video later on when I’m not at work (streaming is no longer allowed), and if I see anything else that was missed, I’ll send it through as feedback.

**Comment by valadas** [comment]
Good job, I will also be improving the common components as I touch them to make them accessible. Keyboard navigation is still an issue but we will keep working on that.

**Comment by Cambridgeport90** [comment]
I’ll continue keeping a hazel eye out, and if there’s anything else you need me to do in the meantime, shoot me a mention.

**Pull request merged**
