### PR TITLE
Page localization settings tooltips

### PR DESCRIPTION
**Pull request by mikebigun**
fixes https://github.com/dnnsoftware/Dnn.AdminExperience/issues/414

See result below. This will help customers a lot when configuring page/module settings.

image

### CODE REVIEW

**Comment by mitchelsellers** [comment]
@dnnsoftware/tag Thoughts on including this in 9.3.0?  Not a high-risk item, but don't want to unnecessarily add changes at this stage of the game

**Comment by iJungleboy** [comment]
@dnnsoftware/tag IMHO it looks trivial, but I would like to kind of "standardize" that we don't add out-of-scope micro-improvements when a release is already rolling. These things tend to backfire - so rather for 9.3.1 or 9.4.0

**Comment by sleupold** [comment]
I agree with @iJungleboy, especially as this is an enhancement, not a fix and the code modification is not trivial (would require a new RC)

**Comment by bdukes** [comment]
Agreed, this should be held for 9.3.1

**Comment by valadas** [comment]
It looks trivial and I love it, but just because we are already on RC2 I would hold it for 9.3.1 to be extra safe.

**Comment by mikebigun** [comment]
Dear community, I'm closing this PR in favor of https://github.com/dnnsoftware/Dnn.AdminExperience/pull/435 which is targeted to `development`.

**Pull request closed without merging**
