### PR TITLE
Set PortalId of user to masterportalid as all users are moved to mast…

### LINKED ISSUE #50: In SiteGroup, Users should be delete-able from PersonaBar UI from child portal of SiteGroup
## Description of bug
Users are not getting delete from portal-site of SiteGroup via PersonaBar UI

## Block Issue
This is blocking #52 

## Steps to reproduce
- Installed engage_9.2.2
- Create child sites with users with Directory option i.e. http://{website1}/child1
- Create Site-Group based on child sites
- Browse to child site i.e. http://{website1}/child1
- Login in as host
- Go to PB > Manage > Users
- Click on right most (...) then click on "Delete-User"
- After that would see message "User have been deleted successfully"
- Goto PB > Content> Recyclebin > Users 
 
## Current result
Users not present and reappear in PB > Manage > Users 

## Expected result
 User should be present 

## Affected version
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1

### PR DESCRIPTION
**Pull request by Mohtshum**
…er site

Fix #50

### CODE REVIEW

**Review by tpluscode — COMMENTED** [review]
Maybe the change should be applied to `UserController` instead?

**Comment by Mohtshum** [comment]
Yeah to keep breaking changes minimum I did make changes in Dnn.AdminExperience Repo. Anyway I submit it again for platform

**Comment by tpluscode** [comment]
What is the opinion of @dnnsoftware/tag ?

**Comment by Mohtshum** [comment]
For platform PR is https://github.com/dnnsoftware/Dnn.Platform/pull/2274

**Pull request closed without merging**
