### PR TITLE
Removes the users exportable code and builds it

### LINKED ISSUE #291: Evoq Products like Engage is having old UsersCommon Bundle, which is causing issue for in PB > Manage > Users ( Clicking role icon on user blank screen)
## Description of bug
Evoq Products like Engage is having old UsersCommon Bundle, which is causing issue for in PB > Manage > Users ( Clicking role icon on user blank screen)

## Steps to reproduce
1. Login as Host
2. Go to PB > Manage > Users 
3. Click on Role icon for any registered user

## Current result
Blank screen

## Expected result
It should show dropdown to add role for the user

## Affected version
* [x] 9.3.0

### PR DESCRIPTION
**Pull request by valadas**
## Summary
The Users module has an exported javascript file that is reused by something in EVOQ. Because that was missed in our corrections to how the bundles are handled, this one was not being built.

This pull request removes that bundle, adds it to the gitignore and adds a build step to run yarn on it before the rest of the build steps.

Closes #291 and Closes #292

### CODE REVIEW

**Comment by daguiler** [comment]
LGTM. I can see the new build in the log:
```
RunYarnExportables:
  D:\a\1\s\packages\Yarn.MSBuild.1.7.0\dist\bin\yarn.cmd install 
  yarn install v1.7.0
  [1/4] Resolving packages...
  [2/4] Fetching packages...
  info fsevents@1.2.4: The platform "win32" is incompatible with this module.
  info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
  [3/4] Linking dependencies...
  warning "@dnnsoftware/dnn-react-common > react-slider@0.11.2" has unmet peer dependency "create-react-class@^15.6".
  warning " > react-redux@5.1.1" has unmet peer dependency "redux@^2.0.0 || ^3.0.0 || ^4.0.0-0".
  [4/4] Building fresh packages...
  Done in 12.57s.
  D:\a\1\s\packages\Yarn.MSBuild.1.7.0\dist\bin\yarn.cmd run build 
  yarn run v1.7.0
  $ set NODE_ENV=production&&webpack -p
  Hash: f1fa78d94377a7544160
  Version: webpack 4.26.1
  Time: 10712ms
  Built at: 2019-01-07 07:37:29
           Asset     Size  Chunks                    Chunk Names
  UsersCommon.js  902 KiB       0  [emitted]  [big]  main
  Entrypoint main [big] = UsersCommon.js
    [0] external "window.dnn.nodeModules.React" 42 bytes {0} [built]
    [1] external "window.dnn.nodeModules.CommonComponents" 42 bytes {0} [built]
    [4] external "window.dnn.nodeModules.ReactRedux" 42 bytes {0} [built]
   [37] ./src/Components/UserTable/DetailRow/style.less 1.23 KiB {0} [built]
   [38] external "window.dnn.nodeModules.Moment" 42 bytes {0} [built]
   [39] ./src/Components/CreateUserBox/style.less 1.21 KiB {0} [built]
   [40] ./src/Components/UserTable/UserSettings/style.less 1.23 KiB {0} [built]
   [42] ./src/Components/UserTable/style.less 1.21 KiB {0} [built]
   [45] ./src/Components/UserTable/HeaderRow/style.less 1.23 KiB {0} [built]
   [54] ./src/Components/common/CollapsibleSwitcher/style.less 1.23 KiB {0} [built]
   [60] ./src/Components/UserTable/EditProfile/style.less 1.23 KiB {0} [built]
   [64] ./src/Components/UserTable/UsersRoles/style.less 1.23 KiB {0} [built]
  [109] ./node_modules/css-loader!./node_modules/less-loader/dist/cjs.js!./src/Components/UserTable/style.less 393 bytes {0} [built]
  [110] ./src/Components/FiltersBar/style.less 1.21 KiB {0} [built]
  [112] ./index.jsx + 30 modules 152 KiB {0} [built]
        | ./index.jsx 510 bytes [built]
        | ./src/actionTypes/index.js 46 bytes [built]
        | ./src/actions/index.js 72 bytes [built]
        | ./src/Components/index.js 109 bytes [built]
        | ./src/reducers/index.js 46 bytes [built]
        | ./src/actionTypes/users.js 751 bytes [built]
        | ./src/actions/users.js 7.53 KiB [built]
        | ./src/Components/UserTable/index.jsx 9.53 KiB [built]
        | ./src/Components/FiltersBar/index.jsx 6.1 KiB [built]
        | ./src/reducers/users.js 6.49 KiB [built]
        | ./src/Components/UserTable/HeaderRow/index.jsx 3.2 KiB [built]
        | ../utils/index.jsx 118 bytes [built]
        | ./src/helpers.js 4.58 KiB [built]
        | ../localization/index.jsx 164 bytes [built]
        | ./src/services/index.js 72 bytes [built]
        |     + 16 hidden modules
      + 98 hidden modules
  
  WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
  This can impact web performance.
  Assets: 
    UsersCommon.js (902 KiB)
  
  WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
  Entrypoints:
    main (902 KiB)
        UsersCommon.js
  
  
  WARNING in webpack performance recommendations: 
  You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
  For more info visit https://webpack.js.org/guides/code-splitting/
  Done in 12.37s.
```

I also see some warnings about peer dependencies.
About size, previous bundle was also around 900 KB.

**Review by daguiler — APPROVED** [review]

**Comment by ohine** [comment]
Thanks for handling getting this fixed correctly @valadas!

However, I still have some questions for ESW on the actual problem. I don't see anything non-functional in the users module prior to this change. If this is truly something only Evoq is using, then I think this needs to be moved into the Evoq CI process and not the Platform. 

What is the exact purpose of this bundle @daguiler?

**Comment by daguiler** [comment]
Hard to say for me @ohine. Only few changes in its [history](https://github.com/dnnsoftware/Dnn.AdminExperience/commits/development/Extensions/Manage/Dnn.PersonaBar.Users/admin/personaBar/scripts/exportables/Users/UsersCommon.js), and all recent. What I can see is that it is being referenced and used by PB > Manage > Users. The issue here was that @Mhtshum wasn't aware that he needed to manually update this bundle.

**Comment by daguiler** [comment]
So just to clarify, this bundle is currently required by platform as well as Evoq.

**Comment by daguiler** [comment]
I just noticed it was recently moved. Older changes prior to that are from a year ago.

**Comment by daguiler** [comment]
Gents, we need this merged please. Thanks @dnnsoftware/approvers

**Review by mitchelsellers — APPROVED** [review]

**Pull request merged**
