### PR TITLE
Fixes #56 - you can't get in edit mode or go out of edit mode when there is a hash (#) in the url.

### LINKED ISSUE #56: Can't go and exit edit mode on pages with #
## Description of bug
When user is loged in with edit permissions on a page with with a #xxx at the end of the url.
Then the edit mode pencil and the close edit mode buttons on the bottom of the page (black area) are not working.

## Steps to reproduce
1) create a new page
2) go to that page
3) add #xxxx add the end of the url in the adressbar of the browser (or create a link with #xxx on the page)
4) click edit mode button
5) Bug : nothing happen

(xxx : can be all text)

## Current result
Nothing happend for the user.
The web api call is fired.
But the page refresh don't hapen.

## Expected result
The page don't go to edit mode or go out of edit mode.

## Additional context
This hapen on all pages with javascript that use routing (clientside urls) with #

Error is in EditBar/Dnn.EditBar.UI/editBar/scripts/ExitEditMode.js
line : window.top.location.href = window.top.location.href;

this will maybe solve the problem
window.location.replace(window.top.location.href);
or rediret to page url without de #xxx part
https://stackoverflow.com/questions/503093/how-do-i-redirect-to-another-webpage

## Affected version
DNN 9.2

## Affected browser
tested on chrome on windows 7

### PR DESCRIPTION
**Pull request by sachatrauwaen**
## Summary
Fixes issue #56
Fixe bug : you can't get in edit mode or go out of edit mode when there is a hash (#) in the url.

### CODE REVIEW

**Review by mitchelsellers — APPROVED** [review]
This solution looks to work well, given the use of location.host it also works with non-standard ports.

**Comment by mitchelsellers** [comment]
@sachatrauwaen This for this, full merging will be delayed until we can get the CLA agreement stuff in place, but this WILL get merged for 9.3

**Review by tpluscode — APPROVED** [review]

**Comment by tpluscode** [comment]
@mitchelsellers so this repository is not yet hooked up to the CLA bot?

**Comment by tpluscode** [comment]
@sachatrauwaen please try following this link to trigger CLA: 
https://cla.dotnetfoundation.org/dnnsoftware/Dnn.AdminExperience?pullRequest=57

**Comment by sachatrauwaen** [comment]
@tpluscode I have accepted CLA folowing the link

**Comment by tpluscode** [comment]
strange that the bot did not update the GH status check. 

can we confirm or recreate the bot integration @ohine

**Comment by tpluscode** [comment]
@mitchelsellers do you agree to merge this?

**Review by mitchelsellers — APPROVED** [review]
LGTM

**Pull request merged**
