### PR TITLE
Update "About" information for DNN Platform to be more relevant and current

### LINKED ISSUE #81: About Screen - Evoq License Management and Not DNN Platform Info
## Description of bug
The About screen located in Settings > About appears to be a license management screen for the commerical Evoq products.

Given that this is the DNN Platform, the About screen should have generic information regarding the DNN Platform and not commerical products.

## Steps to reproduce
1. Login to DNN
2. From the Persona Bar, hover over Settings
3. Select About

## Current result
Users of the DNN Platform are presented with an Evoq licensing screen.

## Expected result
Generic information regarding the DNN Platform.

Some types of information that could be displayed are:

- Current version / build info
- Links to current known issues for the version in question
- Links to the release notes for the version in question
- Links to the DNN documentation and help materials
- Etc.

## Affected version
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ x] 9.1
* [x ] 9.0

### PR DESCRIPTION
**Pull request by david-poindexter**
Resolves #81 

## Summary
See the referenced issue(s) for background information.  Following are the implemented items:

- An intro paragraph and logo was added for general "about" info for DNN Platform.
- `Version (Build)` information is now retrieved dynamically and surfaced in the top right corner of the intro box.
- Boxes with links added for DNN Docs, DNN Community and GitHub.
- Title tags added to provide tooltips on hover.

Screenshot 2019-08-04 15 46 21

### CODE REVIEW

**Comment by david-poindexter** [comment]
Okay, no clue why all these commits are a part of this PR - there should have only been two commits.  Let me know if I need to work with someone to resolve this.

**Comment by valadas** [comment]
Yes, something is odd with this, could it be that you started from development and then targeted release/3.0.x after the fact ?

**Comment by david-poindexter** [comment]
@valadas to my knowledge, this is what I did...

1. git checkout development
2. git pull upstream development
3. git checkout -b release/3.0.x
4. git pull upstream release/3.0.x
5. git checkout -b issue-81
6. Make changes
7. git push origin issue-81
8. Create PR (against release/3.0.x branch)

**Comment by david-poindexter** [comment]
New PR submitted #1094

**Pull request closed without merging**
