### PR TITLE
In PB -> Search Users: exact text search replaced by prefix text search

### PR DESCRIPTION
**Pull request by mean2me**
## Summary
In PB -> Search Users: exact text search replaced by prefix text search, since it's what any user expects.

### CODE REVIEW

**Comment by sleupold** [comment]
it would be nice, if "*anything" would still allow a search in the middle (although with bad performance)

**Review by mitchelsellers — CHANGES_REQUESTED** [review]
This code introduces a redundant call into the SearchTextFilter.CleanWildcards method that should not be here.  It is already called in line 513.

**Review by ohine — CHANGES_REQUESTED** [review]
Broken unit tests need to be fixed. https://dotnetfoundation.visualstudio.com/DNN/_build/results?buildId=4502&view=ms.vss-test-web.test-result-details

**Review by mitchelsellers — APPROVED** [review]
Thanks for the fix

**Comment by ohine** [comment]
@mean2me We still have failing unit tests related to this change. This will need to be fixed before we can merge this pull request.

**Review by tpluscode — APPROVED** [review]

**Comment by tpluscode** [comment]
@ohine all good here?

**Review by ohine — APPROVED** [review]

**Pull request merged**
