### PR TITLE
Adds checksums for 9.4.0 Platform

### LINKED ISSUE #1076: checksums missing in security analyzer
Checksums for 9.3.2 and 9.4.0 are currently missing in the security analyzer sums.resources file. This needs to be added before the 9.4.0 release

### PR DESCRIPTION
**Pull request by valadas**
Closes #1076 

Adds checksums for 9.4.0 Platform default.aspx so the security analyser succeeds checking it

### CODE REVIEW

**Comment by mitchelsellers** [comment]
@valadas This should target the 3.0.x branch, and also seems to include some clutter

**Review by david-poindexter — CHANGES_REQUESTED** [review]
This one has, what appears to be, three rogue commits unrelated to this PR.

**Comment by valadas** [comment]
Oh, what happened there, I will resubmit...

**Comment by valadas** [comment]
Oh, I know what happened, I targeted development instead of release/3.0.0 if you can re-review please :)

**Review by david-poindexter — APPROVED** [review]

**Comment by bdukes** [comment]
Any idea why the checksum is different here?  We didn't implement a change to `Default.aspx`, did we?

**Comment by bdukes** [comment]
Looks like https://github.com/dnnsoftware/Dnn.Platform/commit/0cf1b13b2f076b6f7314142c1778ca97c267ba0 introduced a blank line at the end of the file, even though the other change in that commit was reverted (https://github.com/dnnsoftware/Dnn.Platform/commit/75254183340731513228a1508068c608c15ffa2b)

**Review by bdukes — APPROVED** [review]

**Pull request merged**
