### PR TITLE
Settings > Site Settings > Languages > Enable Localized button not changing to the Disable Localized Content automatically

### LINKED ISSUE #417: Settings > Site Settings > Languages > Enable Localized Content button not changing to the Disable Localized Content automatically
## Description of bug
Settings > Site Settings > Languages > Enable Localized Content button not changing to the Disable Localized Content automatically

Expected Result: Disable Localized Content button should be displayed once all the pages gets translated i.e. after step 6.
We should not require to do extra refresh to change the button name from Enable Localized Content to Disable Localized Content

Actual Result: Enable Localized Content button is displayed on the Languages page.
If we refresh the page, then only Enable Localized Content button changes to Disable Localized button

## Steps to reproduce
1) Navigate to Site Settings -> Languages 
2) Make Allow Content Localization toggle button set to ON 
3) Click on Save button 
4) Click on Enable Localized Content 
5) Set the Make All Pages Translatable toggle button to ON 
6) Click on Enable Localized Content

## Current result
Enable Localized Content button is displayed on the Languages page. 
If we refresh the page, then only Enable Localized Content button changes to Disable Localized button

## Expected result
Disable Localized Content button should be displayed once all the pages gets translated i.e. after step 6. 
We should not do extra refresh to change the button name from Enable Localized Content to Disable Localized Content

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser
* [x] Chrome
* [x] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

### PR DESCRIPTION
**Pull request by anishmishra978**
Fixes #417 and #416

### CODE REVIEW

**Comment by valadas** [comment]
Oh, how did you do the draft thing, I am curious ?

**Comment by anishmishra978** [comment]
@valadas 

image

There is an option to create a draft Pull request here. instead of new PR select draft PR

**Review by valadas — APPROVED** [review]
Looks good to me, did a couple tests, appears to work fine.

**Review by daguiler — APPROVED** [review]
Verified to work on latest build

**Pull request merged**
