### PR TITLE
Get-portal &  get-site command blank screen

### LINKED ISSUE #285: DNN Products > Persona Bar > Settings > Prompt > get-portal displays blank screen & console errors
## Description of bug
get-portal and get-site are giving blank screen and errors in console of browser

## Steps to reproduce
1. Log in As Super User in Evoq Engage 
2. Go to Persona Bar > Settings > Prompt 
3. Type command get-portal/get-site 

## Current result
Application executes the command and blank screen is displayed. Console shown below error:
export-bundle.js?cdv=130:90 TypeError: Cannot read property 'toString' of null

## Expected result
Portal/Site information should be displayed. 

## Error log
export-bundle.js?cdv=130:90 TypeError: Cannot read property 'toString' of null

## Affected version
* [x] 9.3.0

### PR DESCRIPTION
**Pull request by Mhtshum**
Fixes #285 

## Summary
Put null check

### CODE REVIEW

**Review by daguiler — APPROVED** [review]

**Comment by mitchelsellers** [comment]
@valadas Thoughts regarding this addition?  I believe your root cause analysis is correct in that this is due to the fact that we had that data issue.

**Comment by valadas** [comment]
I also believe the root cause is the other issue, but I see no harm rechecking it in the module to prevent it from cashing in other situations.

In javascript, undefined is a variable that was declared but never assigned a value, null is when the value null was actually assigned to the variable. But both undefined and null coalesce to false, so:
```javascript
const fldVal = data[fldName] ? data[fldName].toString() : "";
```
would be a shorter way to do it.
I approve this change but will not merge in case @Mhtshum wants to make it shorter. But I will assign the 1.7.0 milestone to make sure we merge this in case @Mhtshum does not update to the shorter version. No big issue in either case.

**Review by valadas — APPROVED** [review]

**Comment by daguiler** [comment]
Well, looking back in the history of the file, it was short in the beginning, and then @Mhtshum added the explicit undefined and the strict equality operator, and now the null. Not sure what was the motivation but it seems we are repeating ourselves. I also see no harm either way.

**Comment by Mhtshum** [comment]
Thanks a lot @daguiler!, Actually in #80 the fix to display "false" values which was getting empty string because of short check. Hence mine initial check is correct for undefined & null.

**Comment by daguiler** [comment]
@Mhtshum Can you please revert to short version as suggested by @valadas?

**Comment by Mhtshum** [comment]
@daguiler and @valadas, As I mentioned short version is giving empty for attribute which have "false" hence undefined and null check is valid.
The issue reported for page which has isDeleted: false, in that case on prompt output we are getting empty result.

**Comment by daguiler** [comment]
Ok, I see what you mean now @Mohtshum. Approving.

**Comment by daguiler** [comment]
May I suggest adding a comment in code so that we don't stumble upon this again?

**Comment by valadas** [comment]
Good catch @Mhtshum

**Pull request merged**
